# compiler avec les headers et les fichiers objets
ft_putchar.o : srcs/ft_putchar.c
	gcc -Wall -Werror -Wextra -Ilib -c srcs/ft_putchar.c -o ft_putchar.o

#creer la bibliotheque
	ar rcs libft.a ft_putchar.o



